// AUTO GENERATED FILE BY @kalissaac/prisma-typegen
// DO NOT EDIT




export interface User {
    id: number,
    email: string,
    password: string,
    salt: string,
    token: string,
    isValidated: boolean,
}

export interface Ad {
    id: number,
    title?: string,
    description?: string,
    type?: string,
    propertyType?: string,
    propertySubType?: string,
    availability?: string,
    address?: string,
    photos: Photo[],
    cadastralIncome?: string,
    isInvestment: boolean,
    isNew: boolean,
    facadeCount?: number,
    floorArea?: number,
    floorCount?: number,
    buildYear?: number,
    propertyState?: string,
    hasGasWaterElectricity: boolean,
    hasSewerConnection: boolean,
    bedroomsCount?: number,
    roomCount?: number,
    bathroomCount?: number,
    showerroomCount?: number,
    toiletCount?: number,
    kitchenCount?: number,
    hasLivingroom: boolean,
    livingroomArea?: number,
    hasDiningroom: boolean,
    diningroomArea?: number,
    hasCellar: boolean,
    cellaArea?: number,
    hasLaudryroom: boolean,
    laudryroomArea?: number,
    hasAttic: boolean,
    atticArea?: number,
    hasOffice: boolean,
    officeArea?: number,
    hasWorkspace: boolean,
    workspaceArea?: number,
    landArea?: number,
    isLandFacingStreet: boolean,
    isLandFlat: boolean,
    isLandRear: boolean,
    isLandWooded: boolean,
    hasGarden: boolean,
    gardenArea?: number,
    hasTerrace: boolean,
    terraceArea?: number,
    hasPool: boolean,
    poolArea?: number,
    heatingType?: string,
    hasHeatPump: boolean,
    hasPhotovoltaicPanels: boolean,
    hasSolarPanels: boolean,
    hasDoubleGlazing: boolean,
    hasWaterHeater: boolean,
    hasAirConditioning: boolean,
    pebScore?: string,
    pebReportNumber?: string,
    pebEnergyConsumption?: string,
    pebCO2Emission?: string,
    pebPrimaryConsumption?: string,
    hasPlanningPermission: boolean,
    isBreachingUrbanPlanning: boolean,
    floodZone?: string,
    contactEmail?: string,
    contactPhone?: string,
    contactMobile?: string,
    contactCallingTime?: string,
}

export interface Photo {
    id: number,
    ad: Ad,
    adId: number,
}
