const localisation = {
  createAd: {
    fr: 'Publier une annonce',
    nl: '',
    de: '',
    en: '',
  },

  common: {
    email: {
      fr: 'Adresse email',
      nl: '',
      de: '',
      en: '',
    },
    password: {
      fr: 'Mot de passe',
      nl: '',
      de: '',
      en: '',
    },
    signIn: {
      fr: 'Connexion',
      nl: '',
      de: '',
      en: '',
    },
    signOut: {
      fr: 'Déconnexion',
      nl: '',
      de: '',
      en: '',
    },
    register: {
      fr: 'Créer un compte',
      nl: '',
      de: '',
      en: '',
    },
    delete: {
      fr: 'Supprimer',
      nl: '',
      de: '',
      en: '',
    },
    back: {
      fr: 'Retour',
      nl: '',
      de: '',
      en: '',
    },
    next: {
      fr: 'Suivant',
      nl: '',
      de: '',
      en: '',
    },
    previous: {
      fr: 'Précédent',
      nl: '',
      de: '',
      en: '',
    },
    done: {
      fr: 'Terminé',
      nl: '',
      de: '',
      en: '',
    },
    optional: {
      fr: 'Facultatif',
      nl: '',
      de: '',
      en: '',
    },
    save: {
      fr: 'Enregistrer',
      nl: '',
      de: '',
      en: '',
    },
    knowMore: {
      fr: 'En savoir plus',
      nl: '',
      de: '',
      en: '',
    },
    validated: {
      fr: 'Validé',
      nl: '',
      de: '',
      en: '',
    },
    selectAnOption: {
      fr: 'Sélectionnez une proposition',
      nl: '',
      de: '',
      en: '',
    },
  },

  ad: {
    general: {
      fr: 'Informations générales',
      nl: '',
      de: '',
      en: '',
    },
    composition: {
      fr: 'Composition du bien',
      nl: '',
      de: '',
      en: '',
    },
    land: {
      fr: 'Terrain',
      nl: '',
      de: '',
      en: '',
    },
    technical: {
      fr: 'Aspects techniques',
      nl: '',
      de: '',
      en: '',
    },
    contact: {
      fr: 'Contact',
      nl: '',
      de: '',
      en: '',
    },
    description: {
      fr: 'Description du bien',
      nl: '',
      de: '',
      en: '',
    },
    type: {
      fr: "Type d'annonce",
      nl: '',
      de: '',
      en: '',
    },
    sell: {
      fr: 'Vendre',
      nl: '',
      de: '',
      en: '',
    },
    rent: {
      fr: 'Louer',
      nl: '',
      de: '',
      en: '',
    },
    propertyType: {
      fr: 'Type de bien',
      nl: '',
      de: '',
      en: '',
    },
    house: {
      fr: 'Maison',
      nl: '',
      de: '',
      en: '',
    },
    apartment: {
      fr: 'Appartement',
      nl: '',
      de: '',
      en: '',
    },
    garage: {
      fr: 'Garage',
      nl: '',
      de: '',
      en: '',
    },
    office: {
      fr: 'Bureau',
      nl: '',
      de: '',
      en: '',
    },
    industry: {
      fr: 'Industrie',
      nl: '',
      de: '',
      en: '',
    },
    commercial: {
      fr: 'Commerce',
      nl: '',
      de: '',
      en: '',
    },
    other: {
      fr: 'Autre',
      nl: '',
      de: '',
      en: '',
    },
    propertySubType: {
      fr: 'Sous-type',
      nl: '',
      de: '',
      en: '',
    },
    availability: {
      fr: 'Disponibilité',
      nl: '',
      de: '',
      en: '',
    },
    onTheDate: {
      fr: 'À partir de',
      nl: '',
      de: '',
      en: '',
    },
    immediately: {
      fr: 'Immédiatement',
      nl: '',
      de: '',
      en: '',
    },
    toBeDefined: {
      fr: 'À définir',
      nl: '',
      de: '',
      en: '',
    },
    availabilityDate: {
      fr: 'Disponible le',
      nl: '',
      de: '',
      en: '',
    },
    address: {
      fr: 'Adresse du bien',
      nl: '',
      de: '',
      en: '',
    },
    price: {
      fr: 'Prix demandé',
      nl: '',
      de: '',
      en: '',
    },
    photos: {
      fr: 'Photos',
      nl: '',
      de: '',
      en: '',
    },
    cadastralIncome: {
      fr: 'Revenu cadastral',
      nl: '',
      de: '',
      en: '',
    },
    isInvestment: {
      fr: 'Immeuble de rapport',
      nl: '',
      de: '',
      en: '',
    },
    isNew: {
      fr: 'Nouvelle construction',
      nl: '',
      de: '',
      en: '',
    },
    facadeCount: {
      fr: 'Nombre de façades',
      nl: '',
      de: '',
      en: '',
    },
    floorArea: {
      fr: 'Surface totale',
      nl: '',
      de: '',
      en: '',
    },
    floorCount: {
      fr: "Nombre d'étages",
      nl: '',
      de: '',
      en: '',
    },
    buildYear: {
      fr: 'Année de construction',
      nl: '',
      de: '',
      en: '',
    },
    propertyState: {
      fr: 'État du bâtiment',
      nl: '',
      de: '',
      en: '',
    },
    notDefined: {
      fr: 'Non défini',
      nl: '',
      de: '',
      en: '',
    },
    good: {
      fr: 'Bon',
      nl: '',
      de: '',
      en: '',
    },
    asNew: {
      fr: 'Excellent état',
      nl: '',
      de: '',
      en: '',
    },
    toRestore: {
      fr: 'À restaurer',
      nl: '',
      de: '',
      en: '',
    },
    renovated: {
      fr: 'Fraîchement rénové',
      nl: '',
      de: '',
      en: '',
    },
    toRefurbish: {
      fr: 'À rafraichir',
      nl: '',
      de: '',
      en: '',
    },
    toRenovate: {
      fr: 'À rénover',
      nl: '',
      de: '',
      en: '',
    },
    hasGasWaterElectricity: {
      fr: 'Eau / gaz / électricité',
      nl: '',
      de: '',
      en: '',
    },
    hasSewerConnection: {
      fr: "Raccordement à l'égout",
      nl: '',
      de: '',
      en: '',
    },
    bedroomCount: {
      fr: 'Nombre de chambres',
      nl: '',
      de: '',
      en: '',
    },
    bedroomArea: {
      fr: 'Surface de la chambre',
      nl: '',
      de: '',
      en: '',
    },
    roomCount: {
      fr: 'Nombre de pièces',
      nl: '',
      de: '',
      en: '',
    },
    bathroomCount: {
      fr: 'Nombre de salles de bains',
      nl: '',
      de: '',
      en: '',
    },
    showerroomCount: {
      fr: 'Nombre de salles de douches',
      nl: '',
      de: '',
      en: '',
    },
    toiletCount: {
      fr: 'Nombre de toilettes',
      nl: '',
      de: '',
      en: '',
    },
    hasKitchen: {
      fr: 'Cuisine',
      nl: '',
      de: '',
      en: '',
    },
    kitchenArea: {
      fr: 'Surface de la cuisine',
      nl: '',
      de: '',
      en: '',
    },
    hasLivingroom: {
      fr: 'Salon',
      nl: '',
      de: '',
      en: '',
    },
    livingroomArea: {
      fr: 'Surface du salon',
      nl: '',
      de: '',
      en: '',
    },
    hasDiningroom: {
      fr: 'Salle à manger',
      nl: '',
      de: '',
      en: '',
    },
    diningroomArea: {
      fr: 'Surface de la salle à manger',
      nl: '',
      de: '',
      en: '',
    },
    hasCellar: {
      fr: 'Cave',
      nl: '',
      de: '',
      en: '',
    },
    cellaArea: {
      fr: 'Surface de la cave',
      nl: '',
      de: '',
      en: '',
    },
    hasLaudryroom: {
      fr: 'Buandrie',
      nl: '',
      de: '',
      en: '',
    },
    laudryroomArea: {
      fr: 'Surface de la buandrie',
      nl: '',
      de: '',
      en: '',
    },
    hasAttic: {
      fr: 'Grenier',
      nl: '',
      de: '',
      en: '',
    },
    atticArea: {
      fr: 'Surface du grenier',
      nl: '',
      de: '',
      en: '',
    },
    hasOffice: {
      fr: 'Bureau',
      nl: '',
      de: '',
      en: '',
    },
    officeArea: {
      fr: 'Surface du bureau',
      nl: '',
      de: '',
      en: '',
    },
    hasWorkspace: {
      fr: 'Espace de travail',
      nl: '',
      de: '',
      en: '',
    },
    workspaceArea: {
      fr: "Surface de l'espace de travail",
      nl: '',
      de: '',
      en: '',
    },
    landArea: {
      fr: 'Surface du terrain',
      nl: '',
      de: '',
      en: '',
    },
    isLandFacingStreet: {
      fr: 'Terrain à front de rue',
      nl: '',
      de: '',
      en: '',
    },
    isLandFlat: {
      fr: 'Terrain plat',
      nl: '',
      de: '',
      en: '',
    },
    isLandRear: {
      fr: 'Terrain arrière',
      nl: '',
      de: '',
      en: '',
    },
    isLandWooded: {
      fr: 'Terrain boisé',
      nl: '',
      de: '',
      en: '',
    },
    exteriors: {
      fr: 'Extérieurs',
      nl: '',
      de: '',
      en: '',
    },
    hasGarden: {
      fr: 'Jardin',
      nl: '',
      de: '',
      en: '',
    },
    gardenArea: {
      fr: 'Surface du jardin',
      nl: '',
      de: '',
      en: '',
    },
    hasTerrace: {
      fr: 'Terrasse',
      nl: '',
      de: '',
      en: '',
    },
    terraceArea: {
      fr: 'Surface de la terrasse',
      nl: '',
      de: '',
      en: '',
    },
    hasPool: {
      fr: 'Piscine',
      nl: '',
      de: '',
      en: '',
    },
    poolArea: {
      fr: 'Surface de la piscine',
      nl: '',
      de: '',
      en: '',
    },
    equipment: {
      fr: 'Équipement',
      nl: '',
      de: '',
      en: '',
    },
    heatingType: {
      fr: 'Type de chauffage',
      nl: '',
      de: '',
      en: '',
    },
    hasHeatPump: {
      fr: 'Pompe à chaleur',
      nl: '',
      de: '',
      en: '',
    },
    hasPhotovoltaicPanels: {
      fr: 'Panneaux photovoltaïques',
      nl: '',
      de: '',
      en: '',
    },
    hasSolarPanels: {
      fr: 'Panneaux solaires',
      nl: '',
      de: '',
      en: '',
    },
    hasDoubleGlazing: {
      fr: 'Double vitrage',
      nl: '',
      de: '',
      en: '',
    },
    hasWaterHeater: {
      fr: 'Chauffe-eau commun',
      nl: '',
      de: '',
      en: '',
    },
    hasAirConditioning: {
      fr: 'Climatisation',
      nl: '',
      de: '',
      en: '',
    },
    pebCertificate: {
      fr: 'Certificat énergétique',
      nl: '',
      de: '',
      en: '',
    },
    pebScore: {
      fr: 'Classe énergétique',
      nl: '',
      de: '',
      en: '',
    },
    pebReportNumber: {
      fr: 'Numéro de référence du CPEB',
      nl: '',
      de: '',
      en: '',
    },
    pebEnergyConsumption: {
      fr: 'PEB – Consommation énergétique par m²',
      nl: '',
      de: '',
      en: '',
    },
    pebCO2Emission: {
      fr: 'PEB – Émission de CO2',
      nl: '',
      de: '',
      en: '',
    },
    pebPrimaryConsumption: {
      fr: "Consommation théorique totale d'énergie primaire",
      nl: '',
      de: '',
      en: '',
    },
    hasPlanningPermission: {
      fr: "Permis d'urbanisme obtenu",
      nl: '',
      de: '',
      en: '',
    },
    isBreachingUrbanPlanning: {
      fr: 'Procédure pour violation de la réglementation urbanistique',
      nl: '',
      de: '',
      en: '',
    },
    floodZone: {
      fr: 'Zones inondables',
      nl: '',
      de: '',
      en: '',
    },
    contactEmail: {
      fr: 'Adresse email',
      nl: '',
      de: '',
      en: '',
    },
    contactPhone: {
      fr: 'Numéro de téléphone fixe',
      nl: '',
      de: '',
      en: '',
    },
    contactMobile: {
      fr: 'Numéro de GSM',
      nl: '',
      de: '',
      en: '',
    },
    contactCallingTime: {
      fr: "Heures d'appel",
      nl: '',
      de: '',
      en: '',
    },
    kwhm2: {
      fr: 'kWh/m²',
      nl: '',
      de: '',
      en: '',
    },
    kwhyear: {
      fr: 'kWh/an',
      nl: '',
      de: '',
      en: '',
    },
  },

  errors: {
    emailExist: {
      fr: "L'adresse email que vous avez introduite a déjà été utilisée.",
      nl: '',
      de: '',
      en: '',
    },
    badPassword: {
      fr: 'Le mot de passe que vous avez introduit est incorrect.',
      nl: '',
      de: '',
      en: '',
    },
    userDoesNotExist: {
      fr: "L'adresse email que vous avez introduit n'existe pas dans notre base de donnée.",
      nl: '',
      de: '',
      en: '',
    },
    error: {
      fr: 'Une erreur est survenue.',
      nl: '',
      de: '',
      en: '',
    },
  },
}

export const getLocal = (hierarchy: Array<string>) => {
  const chosenLanguage: string = 'fr'
  let target: any = localisation

  try {
    for (let item of hierarchy) {
      target = target[item]
    }

    if (target[chosenLanguage]) {
      return target[chosenLanguage]
    } else {
      return hierarchy[hierarchy.length - 1]
    }
  } catch (e) {
    return hierarchy[hierarchy.length - 1]
  }
}
